import type { Candidate, Referrer, TrackedRequest } from './types';

export const mockCandidates: Candidate[] = [
  {
    id: '1',
    name: 'Alex Johnson',
    avatar: 'https://placehold.co/100x100.png',
    role: 'Senior Frontend Developer',
    company: 'TechCorp',
    salary: 120000,
    skills: ['React', 'TypeScript', 'Next.js', 'GraphQL'],
    location: 'San Francisco, CA',
    experience: 5,
    status: 'Pending',
    jobPostUrl: 'https://example.com/job/1',
    targetCompanies: ['TechCorp', 'CloudWorks'],
  },
  {
    id: '2',
    name: 'Maria Garcia',
    avatar: 'https://placehold.co/100x100.png',
    role: 'Product Manager',
    company: 'InnovateX',
    salary: 140000,
    skills: ['Agile', 'Roadmapping', 'User Research', 'JIRA'],
    location: 'New York, NY',
    experience: 6,
    status: 'Viewed',
    jobPostUrl: 'https://example.com/job/2',
    targetCompanies: ['InnovateX', 'DataDriven Inc.'],
  },
  {
    id: '3',
    name: 'Sam Chen',
    avatar: 'https://placehold.co/100x100.png',
    role: 'UX/UI Designer',
    company: 'Creative Solutions',
    salary: 95000,
    skills: ['Figma', 'Sketch', 'Prototyping', 'User Testing'],
    location: 'Austin, TX',
    experience: 3,
    status: 'Referred',
    jobPostUrl: 'https://example.com/job/3',
    targetCompanies: ['Creative Solutions', 'TechCorp'],
  },
  {
    id: '4',
    name: 'Priya Patel',
    avatar: 'https://placehold.co/100x100.png',
    role: 'Data Scientist',
    company: 'DataDriven Inc.',
    salary: 135000,
    skills: ['Python', 'Machine Learning', 'SQL', 'Tableau'],
    location: 'Chicago, IL',
    experience: 4,
    status: 'Not a Fit',
    jobPostUrl: 'https://example.com/job/4',
    targetCompanies: ['DataDriven Inc.', 'CloudWorks'],
  },
  {
    id: '5',
    name: 'Ben Carter',
    avatar: 'https://placehold.co/100x100.png',
    role: 'DevOps Engineer',
    company: 'CloudWorks',
    salary: 125000,
    skills: ['AWS', 'Docker', 'Kubernetes', 'Terraform'],
    location: 'Seattle, WA',
    experience: 7,
    status: 'Pending',
    jobPostUrl: 'https://example.com/job/5',
    targetCompanies: ['CloudWorks', 'InnovateX'],
  },
   {
    id: '6',
    name: 'Olivia Martinez',
    avatar: 'https://placehold.co/100x100.png',
    role: 'Marketing Manager',
    company: 'InnovateX',
    salary: 110000,
    skills: ['SEO', 'Content Marketing', 'Google Analytics'],
    location: 'New York, NY',
    experience: 4,
    status: 'Viewed',
    jobPostUrl: 'https://example.com/job/6',
    targetCompanies: ['InnovateX', 'Creative Solutions'],
  },
];

export const mockReferrers: Referrer[] = [
  {
    id: 'r1',
    name: 'John Smith',
    avatar: 'https://placehold.co/100x100.png',
    role: 'Senior Software Engineer',
    company: 'TechCorp',
    location: 'San Francisco, CA',
    specialties: ['Frontend', 'React', 'Cloud'],
    connections: 500,
  },
  {
    id: 'r2',
    name: 'Emily Jones',
    avatar: 'https://placehold.co/100x100.png',
    role: 'Engineering Manager',
    company: 'InnovateX',
    location: 'New York, NY',
    specialties: ['Backend', 'Leadership', 'Scaling'],
    connections: 450,
  },
  {
    id: 'r3',
    name: 'Michael Brown',
    avatar: 'https://placehold.co/100x100.png',
    role: 'Recruiter',
    company: 'Creative Solutions',
    location: 'Austin, TX',
    specialties: ['Tech Recruiting', 'Sourcing'],
    connections: 1200,
  },
  {
    id: 'r4',
    name: 'Jessica Davis',
    avatar: 'https://placehold.co/100x100.png',
    role: 'Product Lead',
    company: 'DataDriven Inc.',
    location: 'Chicago, IL',
    specialties: ['Product Strategy', 'UX', 'Mobile'],
    connections: 700,
  },
  {
    id: 'r5',
    name: 'David Wilson',
    avatar: 'https://placehold.co/100x100.png',
    role: 'Senior DevOps Engineer',
    company: 'CloudWorks',
    location: 'Seattle, WA',
    specialties: ['AWS', 'CI/CD', 'Infrastructure'],
    connections: 600,
  },
   {
    id: 'r6',
    name: 'Sarah Miller',
    avatar: 'https://placehold.co/100x100.png',
    role: 'Data Scientist',
    company: 'TechCorp',
    location: 'San Francisco, CA',
    specialties: ['Machine Learning', 'Python', 'Analytics'],
    connections: 300,
  },
];

export const mockTrackedRequests: TrackedRequest[] = [
  {
    id: 'tr1',
    referrer: mockReferrers[0], // John Smith
    status: 'Resume Downloaded',
    requestedAt: '2024-07-26',
  },
  {
    id: 'tr2',
    referrer: mockReferrers[1], // Emily Jones
    status: 'Pending',
    requestedAt: '2024-07-25',
  },
  {
    id: 'tr3',
    referrer: mockReferrers[4], // David Wilson
    status: 'Cancelled',
    cancellationReason: 'Not a good fit for current openings',
    requestedAt: '2024-07-24',
  },
    {
    id: 'tr4',
    referrer: mockReferrers[5], // Sarah Miller
    status: 'Cancelled',
    cancellationReason: 'Experience level does not match',
    requestedAt: '2024-07-22',
  },
];
