import type { Candidate } from './types';

export const mockCandidates: Candidate[] = [
  {
    id: '1',
    name: 'Alex Johnson',
    avatar: 'https://placehold.co/100x100.png',
    role: 'Senior Frontend Developer',
    company: 'TechCorp',
    salary: 120000,
    skills: ['React', 'TypeScript', 'Next.js', 'GraphQL'],
    location: 'San Francisco, CA',
    status: 'Pending',
    jobPostUrl: 'https://example.com/job/1',
  },
  {
    id: '2',
    name: 'Maria Garcia',
    avatar: 'https://placehold.co/100x100.png',
    role: 'Product Manager',
    company: 'InnovateX',
    salary: 140000,
    skills: ['Agile', 'Roadmapping', 'User Research', 'JIRA'],
    location: 'New York, NY',
    status: 'Viewed',
    jobPostUrl: 'https://example.com/job/2',
  },
  {
    id: '3',
    name: 'Sam Chen',
    avatar: 'https://placehold.co/100x100.png',
    role: 'UX/UI Designer',
    company: 'Creative Solutions',
    salary: 95000,
    skills: ['Figma', 'Sketch', 'Prototyping', 'User Testing'],
    location: 'Austin, TX',
    status: 'Referred',
    jobPostUrl: 'https://example.com/job/3',
  },
  {
    id: '4',
    name: 'Priya Patel',
    avatar: 'https://placehold.co/100x100.png',
    role: 'Data Scientist',
    company: 'DataDriven Inc.',
    salary: 135000,
    skills: ['Python', 'Machine Learning', 'SQL', 'Tableau'],
    location: 'Chicago, IL',
    status: 'Not a Fit',
    jobPostUrl: 'https://example.com/job/4',
  },
  {
    id: '5',
    name: 'Ben Carter',
    avatar: 'https://placehold.co/100x100.png',
    role: 'DevOps Engineer',
    company: 'CloudWorks',
    salary: 125000,
    skills: ['AWS', 'Docker', 'Kubernetes', 'Terraform'],
    location: 'Seattle, WA',
    status: 'Pending',
    jobPostUrl: 'https://example.com/job/5',
  },
   {
    id: '6',
    name: 'Olivia Martinez',
    avatar: 'https://placehold.co/100x100.png',
    role: 'Marketing Manager',
    company: 'InnovateX',
    salary: 110000,
    skills: ['SEO', 'Content Marketing', 'Google Analytics'],
    location: 'New York, NY',
    status: 'Viewed',
    jobPostUrl: 'https://example.com/job/6',
  },
];
